leftnav:
- identifier: 60fff609-2ca6-e36d-7fa1-b5b09deac920
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 62c09cc4-8057-e00f-c34b-04af4963ce51
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9f687754-afaa-e41a-47d7-85516c30b275
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 2b73a700-3d21-6417-3921-20167e6a6ee9
  name: Labs
  pageRef: /pages/labs/
  weight: 40
- identifier: 1ed20545-14e0-a2b2-11c3-5a783333e95d
  name: Projects
  pageRef: /pages/projects
  weight: 50
- identifier: 86d191ad-6897-41a0-4bf1-0226b04ae992
  name: Lab Software
  pageRef: /pages/lab-software
  weight: 60
- identifier: 10bc4420-56a8-8eaf-011f-1e0381b8f295
  name: Lab Database
  pageRef: /pages/lab-database
  weight: 70
